{{ if .Values.pullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-pullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "<%= cookiecutter.project_slug | to_lower_camel %>.pullSecret" . }}
{{- end }}
