apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-api
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: http
